import random
from enum import Enum
from ex0.CreatureCard import CreatureCard
from ex1.SpellCard import SpellCard
from ex1.ArtifactCard import ArtifactCard
from ex3.CardFactory import CardFactory


class CreatureType(Enum):
    """
    Enumeration of supported creature types in the fantasy card set.

    This enum defines the valid creature categories that the
    FantasyCardFactory can generate.
    """

    DRAGON = "dragon"
    GOBLIN = "goblin"
# limit the valid values can only be these two, otherwise error


class SpellType(Enum):
    """
    Enumeration of supported spell types.

    This currently contains a single spell type but can be extended
    in the future to support additional fantasy spells.
    """

    FIREBALL = "fireball"


class ArtifactType(Enum):
    """
    Enumeration of supported artifact types.

    Artifacts represent permanent objects that provide ongoing effects
    during gameplay.
    """

    MANA_RING = "mana_ring"


class FantasyCardFactory(CardFactory):
    """
    Concrete implementation of the CardFactory for a fantasy-themed card set.

    This factory is responsible for creating fantasy-style cards such as
    dragons, goblins, spells, and magical artifacts.

    It encapsulates all object creation logic so the game engine does not
    need to know how specific cards are constructed.
    """

    def get_supported_types(self) -> dict:
        return {
            "creatures": [CreatureType.DRAGON.value,
                          CreatureType.GOBLIN.value],
            "spells": [SpellType.FIREBALL.value],
            "artifacts": [ArtifactType.MANA_RING.value]
        }

    def create_creature(self, name_or_power: str | int | None = None):
        """
        Create a fantasy creature card.

        The behavior of this method depends on the provided argument:

        - If a string is provided, the method attempts to match a creature
          type name (e.g., "dragon", "goblin").
        - If an integer is provided, the method returns a default low-cost
          creature (Goblin Warrior) as a simplified example.
        - If None is provided, a creature type is randomly selected.

        Args:
            name_or_power (str | int | None):
                Optional hint that influences the creature type
                generated by the factory.

        Returns:
            CreatureCard: A newly created creature card instance.
        """

        if isinstance(name_or_power, str):
            key = name_or_power.strip().lower()
        elif isinstance(name_or_power, int):
            key = CreatureType.GOBLIN.value
        else:
            key = random.choice([CreatureType.DRAGON.value,
                                 CreatureType.GOBLIN.value])

        if key == CreatureType.DRAGON.value:
            return CreatureCard("Fire Dragon", 5, "Legendary", 7, 5)
        return CreatureCard("Goblin Warrior", 2, "Common", 5, 2)

    def create_spell(self, name_or_power: str | int | None = None):
        """
        Create a fantasy spell card.

        If the provided argument matches the supported spell type
        "fireball", a Fireball spell card is created. Otherwise,
        the factory returns a default Lightning Bolt spell.

        Args:
            name_or_power (str | int | None):
                Optional hint indicating the desired spell type.

        Returns:
            SpellCard: A spell card instance.
        """

        if isinstance(name_or_power,
                      str) and name_or_power.strip().lower() == "fireball":
            return SpellCard("Fireball", 4, "Rare", "damage")
        return SpellCard("Lightning Bolt", 3, "Common", "damage")

    def create_artifact(self, name_or_power: str | int | None = None):
        """
        Create a fantasy artifact card.

        This simplified implementation always produces a Mana Ring,
        a magical artifact that grants additional mana generation.

        Args:
            name_or_power (str | int | None):
                Optional parameter reserved for future extensions.

        Returns:
            ArtifactCard: A Mana Ring artifact card.
        """

        return ArtifactCard("Mana Ring", 2, "Rare", durability=3,
                            effect="+1 mana per turn")

    def create_themed_deck(self, size: int) -> dict:
        """
        Generate a small themed fantasy deck.

        The deck is composed of a predefined set of fantasy cards
        (dragon, goblin, lightning spell). The size parameter
        controls how many cards from this set are included.

        Args:
            size (int):
                The number of cards to include in the generated hand.
                Must be a positive integer.

        Returns:
            dict: A dictionary representing the initial game state
            containing:
                - "hand": list of cards available to the player
                - "battlefield": list of cards currently in play

        Raises:
            ValueError: If size is not a positive integer.
        """

        if not isinstance(size, int) or size <= 0:
            raise ValueError("size must be a positive int")

        hand = [
            self.create_creature("dragon"),
            self.create_creature("goblin"),
            self.create_spell("lightning")
        ][:size]  # have 0->size-1 cards

        return {"hand": hand, "battlefield": []}


# 1. name_or_power: str | int | None = None 是 Python 中函数参数的类型注解和默认值声明，具体含义如下：
# str | int | None：这是一个类型联合（union），表示参数 name_or_power 可以接受三种类型的值：
# str：字符串类型，例如 "dragon"。
# int：整数类型，例如 5。
# None：空值，表示没有传入参数。
# = None：这是参数的默认值。如果在调用函数时没有提供该参数，则自动取值为 None
